[config]
save_dir="results/optenv_valuegrad_sinwave_sgd2/"
exp_file="experiment/experiment.jl"
exp_module_name = "Main"
exp_func_name = "run_experiment"
pre_exp_files = []
arg_iter_type = "iter"
post_exp = "gen_metric_dict"

[static_args]
init_num_episodes = 128
init_policy = "default"
num_episodes = 10000
num_grad_steps = 10
num_env_steps = 1
batch_size = 128
max_num_episodes = 256
max_episode_length = 1000
history_window = 1
BufferType = "TransitionReplayBuffer"
hidden_size = 128
activation = "relu"
num_layers = 0
gamma = 1.0
optimizer = "ADAM"
replan = 0
bootstrap = true
curriculum = false
overlap = true
shaping = false
force = "online"
gpu = true
corruption_rate = 0.0
drop_rate = 0.0
reg = false
continuing = false
AgentType = "MCValue"
recurrent_action_dim = 0
update_freq = 10
predict_window = 0
behavior = "grad_init"
run_traj = false
burn_in = 2
measurement_funcs = """
                  online_returns,
                  buffer_loss,
                  estimate_startvalue,
                  estimate_termvalue,
                  mc_buffer_loss,
                  optimize_student_metrics,
"""
callback_funcs = """
               optimize_student,
"""

[sweep_args]
lr = "[0.001, 0.0005, 0.0001]"
seed = "using Random; rand(MersenneTwister(10010111215), 1:10^10, 10)"
state_representation = ["PE-y_20"]
EnvType = ["OptEnv-FiniteHorizon1-sinWave-SGD"]
pooling_func = ["attention", "mean"]
